title_primary: "十月的东山岛" # the bigger text
title_secondary: "观海" # the smaller text
keywords:

twitter: #username
rss: atom.xml
weibo: #username/id
instagram: #username
github: chaseSpace

# 尝试了 Livere, disqus 都搭建失败
# Choose the comment service according to your need.
# Please do not use the two services at the same time.
livere: # [data-uid] on livere.com
# Comments
disqus:
# disqus_shortname: chasespace # 开启此项也不行
dove:

# Set true to show the page indicator.
showPageCount: true

# Set true to show category or tags behind post titles
showCategories: true
showTags: true

# Color scheme
themeStyle: light # light/dark
